prgrms-web-devcourse/Team_Alchomist_ShakeNMatch_FE

- .eslintrc.js
- .storybook/main.js
- tsconfig.json
- tsconfig.path.json
1. ts 린트를 제대로 잡지 못하는 오류를 해결하였습니다.
2. 프로젝트의 Alias 설정을 완료하였습니다.
1. ![image](https://user-images.githubusercontent.com/75013334/143902360-d91cf0a6-0da0-46ef-8520-1cfc0155ffd5.png)
2.1. ![image](https://user-images.githubusercontent.com/75013334/143902243-f82842f9-67f1-4fc1-b4ba-414a4c66177e.png)
2.2. ![image](https://user-images.githubusercontent.com/75013334/143903036-6cbacae0-8990-4fc0-af02-6ff559da3c37.png)
1. eslintrc.js 의 속성으로 overrides 를 추가함으로서 ts, tsx 파일에 대한 parserOptions 처리를 진행하였습니다. 해당 해결방법에 대해서는 추가적인 학습이 필요할듯합니다.
2. Alias 설정을 위의 사진과 같이 진행하였습니다. storybook에서의 Alias 설정도 함께 진행하였습니다.
* 개발환경 세팅에 대한 부분이므로 별도의 코드리뷰 없이 Merge될 PR입니다.
> fix: SM-12 lint Error fix 및 Alias 경로 설정

- src/components/base/Text/styled.ts
- src/components/base/Text/types.ts
- src/models/types.ts
- src/stories/base/Text.stories.tsx
- src/utils/constants/color.ts
- src/utils/constants/index.ts
- src/utils/constants/size.ts
Text 컴포넌트 상수화 진행하였습니다.
color, size에 대한 상수화 진행하였습니다.
> fix: SM-63 Text 컴포넌트 타입 상수화 및 커스텀 설정

- .eslintrc.js
> feat: SM-89 eslint 룰 변경

- src/components/domain/IngredientToggleList/index.tsx
- src/components/domain/TitleSectionContainer/types.ts
> fix: SM-95 오탈자 및 누락된 interface 추가

- src/components/compound/Album/styled.ts
- src/components/domain/CocktailList/index.tsx
- src/components/domain/CocktailList/styled.ts
- src/components/domain/CocktailList/types.ts
- src/stories/domain/CocktailList.stories.tsx
추천 칵테일 결과 리스트 컴포넌트 입니다.
API 호출을 통해 응답받은 데이터를 렌더링 합니다.
+ cocktailList: 서버로부터 응답받은 추천 칵테일 데이터 배열입니다. 만약 빈값인 경우 noResultMsg인 '죄송합니다. 추천 칵테일이 존재하지 않습니다.'가 렌더링 됩니다.
+ noResultMsg: 일치 결과가 없는 경우 출력할 문자열입니다.
서버로부터 응답받은 데이터를 map으로 순회하며 Album 컴포넌트에 넣어줍니다. 애니메이션 효과를 위해 개별 Album 컴포넌트를 StyledMotionWrapper 컴포넌트로 감쌌습니다.
+ 추후 요소들의 크기 수정이 필요합니다
> Feat/sm 84/cocktail list

- src/models/types.ts
> feat: SM-141 Entity Types 정의

- src/components/compound/Album/styled.ts
- src/components/compound/Carousel/CarouselContainer/index.tsx
- src/components/compound/Carousel/CarouselContainer/types.ts
- src/components/compound/Carousel/CarouselItem/index.tsx
- src/components/compound/Carousel/CarouselItem/styled.ts
- src/components/domain/CocktailList/index.tsx
- src/components/domain/CocktailList/styled.ts
- src/components/domain/CocktailList/types.ts
- src/index.tsx
- src/pages/MyPage/index.tsx
- src/pages/MyPage/styled.ts
- src/stories/domain/CocktailList.stories.tsx
- src/stories/domain/IngredientToggleList.stories.tsx
MyPage 기본적인 형태 구현하였습니다.
Carousel에 따라서 우측 결과가 다르게 렌더링 됩니다.
1. CocktailList
> feat: SM-139 MyPage 기본적인기능 구현

- src/components/compound/MenuTab/index.tsx
- src/components/compound/MenuTab/styled.ts
- src/components/compound/MenuTab/types.ts
- src/components/compound/TextToggle/index.tsx
- src/components/compound/TextToggle/types.ts
- src/components/domain/IngredientSelectModal/index.tsx
- src/components/domain/IngredientSelectModal/styled.ts
- src/components/domain/IngredientSelectModal/types.ts
- src/components/domain/IngredientToggleList/index.tsx
- src/components/domain/IngredientToggleList/styled.ts
- src/components/domain/IngredientToggleList/types.ts
- src/components/domain/TitleSectionContainer/index.tsx
- src/components/domain/TitleSectionContainer/types.ts
- src/stories/domain/IngredientSelectModal.stories.tsx
- src/stories/domain/IngredientToggleList.stories.tsx
술장고 페이지에서 열리는 재료 수정 모달창입니다.
컨텍스트가 작업되고나서 좀 더 마무리할 부분이 있습니다.
> Feat/sm 94/ingredient select modal

- src/pages/MainPage/index.tsx
- src/pages/MainPage/styled.ts
> hotfix: 메인페이지 BackButton 수정

- src/pages/ShoppingPage/index.tsx
- src/pages/ShoppingPage/styled.ts
- src/utils/constants/colors.ts
Shopping Page를 구현하였습니다. 
TitleSectionContainer와 ShoppingItem을 조합하여 하나의 페이지를 구성하였습니다.
헤더 부분을 제외하고 구현하였습니다.
더미데이터를 임의로 구성하였습니다.
> feat: SM-150 Shopping Page 구현

- src/components/base/Tooltip/styled.ts
- src/components/domain/Header/index.tsx
- src/components/domain/Header/styled.ts
Header의 Icon에 ToolTip기능을 작성하였습니다.
하단의 commit 내용만 확인하면 됩니다.
commit: 724234964c306073bd70e810d78fb60f344c75da
- ToolTip 위치조정을위해 base ToolTip의 style을 수정하였습니다.
> feat: SM-152 headerToolTip

- src/components/domain/SectionDividerWithTitle/index.tsx
- src/components/domain/SectionDividerWithTitle/types.ts
- src/hooks/useForm.ts
- src/pages/RegisterPage/index.tsx
- src/stories/domain/CocktailReviewModal.stories.tsx
> feat: SM-155 회원가입 api 테스트

- src/components/compound/Album/index.tsx
- src/components/compound/Album/styled.ts
- src/components/compound/Album/types.ts
- src/components/compound/Carousel/CarouselItem/index.tsx
- src/components/compound/Carousel/CarouselItem/styled.ts
- src/components/compound/Carousel/CarouselItem/types.ts
- src/components/domain/CocktailList/styled.ts
- src/components/domain/Header/styled.ts
- src/components/domain/ThemeSelector/index.tsx
- src/components/domain/ThemeSelector/styled.ts
- src/index.tsx
- src/pages/ThemePage/index.tsx
- src/pages/ThemePage/styled.ts
- src/utils/constants/colors.ts
CocktailList 및 Carousel Style 수정 진행하였습니다.
> fix: SM-158 CocktailList, Carousel Style 수정

- src/contexts/Jango/index.tsx
- src/contexts/Jango/types.ts
- src/hooks/useAxios.ts
- src/models/types.ts
- src/pages/JangoPage/index.tsx
- src/pages/SearchPage/index.tsx
- src/routes/index.tsx
- src/utils/apis/cocktail.ts
- src/utils/apis/user.ts
- src/utils/constants/axios.ts
> Feat/sm 164/apis

- src/components/domain/CocktailList/types.ts
- src/hooks/useAxios.ts
- src/pages/SearchPage/index.tsx
- src/utils/apis/cocktail.ts
> Feat/sm 173/search page api

- src/hooks/useAxios.ts
> chore: SM-181 useAxios 오탈자 수정

- src/components/base/Text/index.tsx
- src/components/base/Text/types.ts
- src/components/compound/TextToggle/index.tsx
- src/components/compound/TextToggle/types.ts
- src/components/domain/IngredientCarousel/types.ts
- src/components/domain/IngredientSelectModal/index.tsx
- src/components/domain/IngredientSelectModal/types.ts
- src/components/domain/IngredientToggleList/index.tsx
- src/components/domain/IngredientToggleList/types.ts
- src/models/types.ts
- src/pages/JangoPage/index.tsx
- src/stories/domain/CocktailList.stories.tsx
- src/stories/domain/IngredientCarousel.stories.tsx
- src/stories/domain/IngredientSelectModal.stories.tsx
- src/stories/domain/IngredientToggleList.stories.tsx
api로 받게되는 id type이 number이기 때문에 id type을 모두 number로 변경하였습니다.
타입만 변경하는 이슈이므로 코드리뷰없이 merge진행합니다.
> fix: SM-182 모든 id string에서 number로 변환

- .env
- src/components/domain/CocktailList/styled.ts
- src/components/domain/Header/styled.ts
- src/index.tsx
- src/pages/SearchPage/index.tsx
header의 색상 및 body margin값 등을 수정하였습니다.
> refactor: SM-170 스타일 수정

- src/components/domain/CocktailDetailModal/index.tsx
- src/components/domain/CocktailList/index.tsx
이전 이슈 머지 과정에서 누락된 Album 클릭 이벤트 핸들러 함수 바인딩 작업을 진행했습니다.
https://user-images.githubusercontent.com/44149596/146575820-82d58739-56ef-4e94-a9d3-0d3a7e67ae15.mov
> feat: SM-184 Album에클릭 이벤트 핸들러 함수 바인딩

- src/components/domain/CocktailDetailModal/index.tsx
- src/components/domain/CocktailDetailModal/types.ts
- src/components/domain/CocktailList/index.tsx
DetailModal 뜰때 backgroundSize가 0으로 잡히는 문제를 해결하였습니다.
기존에는 Modal이 mount될때 Menutab도 동시에 mount되도록 로직이 구성되었으나, react가 해당 컴포넌트를 document에 append하기 이전에 offsetHeight 값을 조회하여서 그런지 offsetHeight가 의도와는 다르게 0이 나오는 문제가 있었습니다.
CocktailList가 mount될때, Modal을 미리 띄워둠으로서, 내부 menutab이 mount될때, Modal은 이미 화면에 나타난 상태이므로, offsetHeight 값을 제대로 읽을수 있게 됩니다.
> fix: SM-187 DetailModal 뜰때 backgroundSize가 0으로 잡히는 문제 해결

- src/components/base/Text/styled.ts
- src/components/domain/MainMenuSelector/styled.ts
- src/index.tsx
- src/pages/MainPage/index.tsx
- src/pages/MainPage/styled.ts
MainPage의 스타일을 수정하였습니다.
- theme 에서 jango 로 바로 이동할때, 버튼이 사라지지 않는 문제를 해결하였습니다.
- section 선택시 상세 설명이 나타납니다.
> refactor: SM-185 MainPage 스타일 수정

- src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
- src/components/domain/CocktailDetailModal/IngredientItem/style.ts
- src/components/domain/CocktailDetailModal/index.tsx
- src/routes/index.tsx
> Feat/sm 190/detail modal fix

- src/components/domain/ChangingSpeech/index.tsx
- src/components/domain/ChangingSpeech/styled.ts
- src/components/domain/ChangingSpeech/types.ts
> fix: SM-198 검색봇이 보이지 않을 때도 뒷배경을 클릭할 수 없었던 문제 해결

- src/components/base/Input/index.tsx
- src/components/base/Input/style.tsx
- src/components/base/Input/types.ts
- src/components/compound/Carousel/CarouselItem/styled.ts
- src/components/domain/CocktailList/index.tsx
- src/components/domain/SearchBot/index.tsx
- src/components/domain/SearchBot/styled.ts
- src/components/domain/SearchBot/types.ts
- src/pages/ThemePage/index.tsx
- src/pages/ThemePage/styled.ts
작은 수정들 진행하였습니다.
1. Input Component에 alignCenter prop 추가하였습니다
2. Carousel의 shadow 수정하였습니다
3. Cocktail Icon 적용을 index + cocktail.id 기준으로 변경하였습니다.
4. Searchbot Style 수정하였습니다.
5. ThemePage Style 변경하였습니다.
style 수정사항이므로 바로 merge 진행하겠습니다
> Fix/sm 202/bug fix

- src/components/base/Image/index.tsx
- src/components/base/Input/index.tsx
- src/components/base/Input/style.tsx
- src/components/base/Input/types.ts
- src/components/compound/Carousel/CarouselItem/styled.ts
- src/components/domain/CocktailList/index.tsx
- src/components/domain/SearchBot/index.tsx
- src/components/domain/SearchBot/styled.ts
- src/components/domain/SearchBot/types.ts
- src/pages/ThemePage/index.tsx
- src/pages/ThemePage/styled.ts
추가적인 bug fix 진행하였습니다
1. image onLoad시에 visibility: true로 변경하게끔 하였습니다.
> fix: SM-202 bug fix

- src/components/domain/CocktailDetailModal/index.tsx
- src/components/domain/CocktailDetailModal/types.ts
- src/components/domain/CocktailList/index.tsx
마지막 브랜치를 merge 하면서, 기존 CocktailList 컴포넌트에서 conflict가 있었던 지점을 잘못 병합한 것 같습니다.
이로 인해 CocktailDetailModal에서 메뉴탭 background 문제, 리뷰 작성 버튼을 클릭하면 제대로 동작하지 않는 문제 등이 있었습니다.
> fix: SM-208 CocktailList 머지 conflict 병합 오류 수정

- src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
- src/components/domain/KaKaoButton/index.tsx
- src/pages/ShoppingPage/index.tsx
shopping page와 login 창이 새로운 창으로 열리게 수정하였으며, 열리는 위치도 수정하였습니다.
1. window의 innerHeight, innerWidth 와 screenY, screenX 값을 활용하여 중앙위치로 창이 open 되게끔 설정하였습니다.
> refactor: SM-202 shopping page 새창으로 열리는 옵션 수정 및 중앙화
